language: java


jobs:
  include:
  - stage: test
    jdk: openjdk11
    script:
    - cd assign_first
    - javac src/fib/Fibonacci.java && java src/fib/Fibonacci
    - cd ..
  
  - stage: test
    jdk: openjdk11
    script:
    - cd texas_hold_em
    - mvn test
    - cd ..

  - stage: test
    jdk: openjdk11
    script:
    - cd todolist
    - mvn test
    - cd ..