language: java


jobs:
  include:
  - stage: test
    jdk: openjdk11
    script:
    - cd assign_first
    - javac src/fib/Fibonacci.java
    - cd ..
  
  - stage: test
    jdk: openjdk11
    script:
    - cd texas_hold_em
    - mvn test
    - cd ..

  - stage: test
    jdk: openjdk11
    script:
    - cd todolist
    - mvn test
    - cd ..

  - stage: deploy to staging
    script: skip
    before_deploy: cd todolist
    deploy: &heroku
      provider: heroku
      app: todo-of-scrum-assignments
      api_key: $HEROKU_AUTH_TOKEN

  - stage: deploy
    before_deploy: cd react_todos
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master