language: java


jobs:
  include:
  - stage: test
    jdk: openjdk11
    script:
    - cd assign_first
    - javac src/fib/Fibonacci.java
    - cd ..
  
  - stage: test
    jdk: openjdk11
    script:
    - cd texas_hold_em
    - mvn test
    - cd ..

  - stage: test
    jdk: openjdk11
    script:
    - cd todolist
    - mvn test
    - cd ..

  - stage: deploy to staging
    script: skip
    before_deploy: cd todolist
    deploy: &heroku
      provider: heroku
      app: todo-of-scrum-assignments
      api_key: $HEROKU_AUTH_TOKEN

  - stage: deploy
    language: node_js
    node_js: 
      - "10"
    before_install:
      - cd react_todos
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_USERNAME
    install:
      - npm install
    script:
      - npm run build
    after_success:
      - rm .gitignore
      - git add build
      - git commit -m "built with travis:JOB $TRAVIS_JOB_NUMBER"
      - git subtree push --prefix react_todos/build https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$TRAVIS_REPO_SLUG gh-pages --force
    deploy:
      on:
        branch: master
